<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\OrdersV20260101\Dto;

use SellingPartnerApi\Dto;

final class DeliveryPreference extends Dto
{
    /**
     * @param  ?string  $dropOffLocation  The drop-off location selected by the customer.
     * @param  ?string  $addressInstruction  Building instructions, nearby landmark, or navigation instructions.
     * @param  ?PreferredDeliveryTime  $deliveryTime  Customer-specified time preferences for when deliveries should be attempted at the destination address.
     * @param  ?string[]  $deliveryCapabilities  A list of miscellaneous delivery capabilities associated with the shipping address.
     */
    public function __construct(
        public ?string $dropOffLocation = null,
        public ?string $addressInstruction = null,
        public ?PreferredDeliveryTime $deliveryTime = null,
        public ?array $deliveryCapabilities = null,
    ) {}
}
