<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\ProductPricingV20220501\Dto;

use SellingPartnerApi\Dto;

final class Points extends Dto
{
    /**
     * @param  ?int  $pointsNumber  The number of points.
     * @param  ?MoneyType  $pointsMonetaryValue  Currency type and monetary value. Schema for demonstrating pricing info.
     */
    public function __construct(
        public ?int $pointsNumber = null,
        public ?MoneyType $pointsMonetaryValue = null,
    ) {}
}
