<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\ProductPricingV20220501\Dto;

use SellingPartnerApi\Dto;

final class SimilarItems extends Dto
{
    protected static array $complexArrayTypes = ['items' => Item::class];

    /**
     * @param  Item[]|null  $items  A list of similar items for the specified ASIN `marketplaceId` combination.
     */
    public function __construct(
        public ?array $items = null,
    ) {}
}
