<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\ProductPricingV0\Dto;

use SellingPartnerApi\Dto;

final class Price extends Dto
{
    protected static array $attributeMap = ['sellerSku' => 'SellerSKU', 'asin' => 'ASIN', 'product' => 'Product'];

    /**
     * @param  string  $status  The status of the operation.
     * @param  ?string  $sellerSku  The seller stock keeping unit (SKU) of the item.
     * @param  ?string  $asin  The Amazon Standard Identification Number (ASIN) of the item.
     * @param  ?Product  $product  An item.
     */
    public function __construct(
        public string $status,
        public ?string $sellerSku = null,
        public ?string $asin = null,
        public ?Product $product = null,
    ) {}
}
