<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\ProductPricingV0\Dto;

use SellingPartnerApi\Dto;

final class PrimeInformationType extends Dto
{
    protected static array $attributeMap = ['isPrime' => 'IsPrime', 'isNationalPrime' => 'IsNationalPrime'];

    /**
     * @param  bool  $isPrime  Indicates whether the offer is an Amazon Prime offer.
     * @param  bool  $isNationalPrime  Indicates whether the offer is an Amazon Prime offer throughout the entire marketplace where it is listed.
     */
    public function __construct(
        public bool $isPrime,
        public bool $isNationalPrime,
    ) {}
}
