<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: SellingPartnerApi\Generator\Generators\RequestGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\ExternalFulfillmentV20240911\Requests;

use Exception;
use Saloon\Enums\Method;
use Saloon\Http\Response;
use SellingPartnerApi\Request;
use SellingPartnerApi\Seller\ExternalFulfillmentV20240911\Responses\ErrorList;
use SellingPartnerApi\Seller\ExternalFulfillmentV20240911\Responses\ShippingOptionsResponse;

/**
 * retrieveShippingOptions
 */
class RetrieveShippingOptions extends Request
{
    protected Method $method = Method::GET;

    /**
     * @param  string  $shipmentId  The ID of the shipment to which the package belongs.
     * @param  string  $packageId  The ID of the package for which you want to retrieve shipping options.
     */
    public function __construct(
        protected string $shipmentId,
        protected string $packageId,
    ) {}

    public function resolveEndpoint(): string
    {
        return "/externalFulfillment/2024-09-11/shipments/{$this->shipmentId}/shippingOptions";
    }

    public function createDtoFromResponse(Response $response): ShippingOptionsResponse|ErrorList
    {
        $status = $response->status();
        $responseCls = match ($status) {
            200 => ShippingOptionsResponse::class,
            400, 403, 404, 409, 413, 415, 422, 429, 500, 503 => ErrorList::class,
            default => throw new Exception("Unhandled response status: {$status}")
        };

        return $responseCls::deserialize($response->json());
    }

    public function defaultQuery(): array
    {
        return array_filter(['packageId' => $this->packageId]);
    }
}
