<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\APlusContentV20201101\Dto;

use SellingPartnerApi\Dto;

final class StandardCompanyLogoModule extends Dto
{
    /**
     * @param  ImageComponent  $companyLogo  A reference to an image, hosted in the A+ Content media library.
     */
    public function __construct(
        public ImageComponent $companyLogo,
    ) {}
}
