<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\CatalogItemsV20201201\Dto;

use SellingPartnerApi\Dto;

final class ItemSummaryByMarketplace extends Dto
{
    /**
     * @param  string  $marketplaceId  Amazon marketplace identifier.
     * @param  ?string  $brandName  Name of the brand associated with an Amazon catalog item.
     * @param  ?string  $browseNode  Identifier of the browse node associated with an Amazon catalog item.
     * @param  ?string  $colorName  Name of the color associated with an Amazon catalog item.
     * @param  ?string  $itemName  Name, or title, associated with an Amazon catalog item.
     * @param  ?string  $manufacturer  Name of the manufacturer associated with an Amazon catalog item.
     * @param  ?string  $modelNumber  Model number associated with an Amazon catalog item.
     * @param  ?string  $sizeName  Name of the size associated with an Amazon catalog item.
     * @param  ?string  $styleName  Name of the style associated with an Amazon catalog item.
     */
    public function __construct(
        public string $marketplaceId,
        public ?string $brandName = null,
        public ?string $browseNode = null,
        public ?string $colorName = null,
        public ?string $itemName = null,
        public ?string $manufacturer = null,
        public ?string $modelNumber = null,
        public ?string $sizeName = null,
        public ?string $styleName = null,
    ) {}
}
