<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\SupplySourcesV20200701\Dto;

use SellingPartnerApi\Dto;

final class DeliveryChannel extends Dto
{
    /**
     * @param  ?OperationalConfiguration  $operationalConfiguration  The operational configuration of `supplySources`.
     */
    public function __construct(
        public ?bool $isSupported = null,
        public ?OperationalConfiguration $operationalConfiguration = null,
    ) {}
}
