<?php
/**
 * GetPreorderInfoResultTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Evers\SellingPartnerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Evers\SellingPartnerApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetPreorderInfoResultTest Class Doc Comment
 *
 * @category    Class
 * @description GetPreorderInfoResult
 * @package     Evers\SellingPartnerApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetPreorderInfoResultTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetPreorderInfoResult"
     */
    public function testGetPreorderInfoResult()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shipment_contains_preorderable_items"
     */
    public function testPropertyShipmentContainsPreorderableItems()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shipment_confirmed_for_preorder"
     */
    public function testPropertyShipmentConfirmedForPreorder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "need_by_date"
     */
    public function testPropertyNeedByDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "confirmed_fulfillable_date"
     */
    public function testPropertyConfirmedFulfillableDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
