<?php
/**
 * ItemEligibilityPreviewTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Amazon\SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for FBA Inbound Eligibilty
 *
 * With the FBA Inbound Eligibility API, you can build applications that let sellers get eligibility previews for items before shipping them to Amazon's fulfillment centers. With this API you can find out if an item is eligible for inbound shipment to Amazon's fulfillment centers in a specific marketplace. You can also find out if an item is eligible for using the manufacturer barcode for FBA inventory tracking. Sellers can use this information to inform their decisions about which items to ship Amazon's fulfillment centers.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Amazon\SellingPartnerApi;

/**
 * ItemEligibilityPreviewTest Class Doc Comment
 *
 * @category    Class
 * @description The response object which contains the ASIN, marketplaceId if required, eligibility program, the eligibility status (boolean), and a list of ineligibility reason codes.
 * @package     Amazon\SellingPartnerApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ItemEligibilityPreviewTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ItemEligibilityPreview"
     */
    public function testItemEligibilityPreview()
    {
    }

    /**
     * Test attribute "asin"
     */
    public function testPropertyAsin()
    {
    }

    /**
     * Test attribute "marketplace_id"
     */
    public function testPropertyMarketplaceId()
    {
    }

    /**
     * Test attribute "program"
     */
    public function testPropertyProgram()
    {
    }

    /**
     * Test attribute "is_eligible_for_program"
     */
    public function testPropertyIsEligibleForProgram()
    {
    }

    /**
     * Test attribute "ineligibility_reason_list"
     */
    public function testPropertyIneligibilityReasonList()
    {
    }
}
