<?php
/**
 * OfferTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Amazon\SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.13
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Amazon\SellingPartnerApi;

/**
 * OfferTypeTest Class Doc Comment
 *
 * @category    Class
 * @description OfferType
 * @package     Amazon\SellingPartnerApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OfferTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OfferType"
     */
    public function testOfferType()
    {
    }

    /**
     * Test attribute "buying_price"
     */
    public function testPropertyBuyingPrice()
    {
    }

    /**
     * Test attribute "regular_price"
     */
    public function testPropertyRegularPrice()
    {
    }

    /**
     * Test attribute "fulfillment_channel"
     */
    public function testPropertyFulfillmentChannel()
    {
    }

    /**
     * Test attribute "item_condition"
     */
    public function testPropertyItemCondition()
    {
    }

    /**
     * Test attribute "item_sub_condition"
     */
    public function testPropertyItemSubCondition()
    {
    }

    /**
     * Test attribute "seller_sku"
     */
    public function testPropertySellerSku()
    {
    }
}
