<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\FinancesV0\Dto;

use SellingPartnerApi\Dto;

final class TaxWithholdingEvent extends Dto
{
    protected static array $attributeMap = [
        'postedDate' => 'PostedDate',
        'baseAmount' => 'BaseAmount',
        'withheldAmount' => 'WithheldAmount',
        'taxWithholdingPeriod' => 'TaxWithholdingPeriod',
    ];

    /**
     * @param  ?\DateTimeInterface  $postedDate  Fields with a schema type of date are in ISO 8601 date time format (for example GroupBeginDate).
     * @param  ?Currency  $baseAmount  A currency type and amount.
     * @param  ?Currency  $withheldAmount  A currency type and amount.
     * @param  ?TaxWithholdingPeriod  $taxWithholdingPeriod  Period which taxwithholding on seller's account is calculated.
     */
    public function __construct(
        public ?\DateTimeInterface $postedDate = null,
        public ?Currency $baseAmount = null,
        public ?Currency $withheldAmount = null,
        public ?TaxWithholdingPeriod $taxWithholdingPeriod = null,
    ) {}
}
