<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\MerchantFulfillmentV0\Dto;

use SellingPartnerApi\Dto;

final class TemporarilyUnavailableCarrier extends Dto
{
    protected static array $attributeMap = ['carrierName' => 'CarrierName'];

    /**
     * @param  string  $carrierName  The name of the carrier.
     */
    public function __construct(
        public string $carrierName,
    ) {}
}
