<?php
/**
 * FeesApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Evers\SellingPartnerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Product Fees
 *
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Evers\SellingPartnerApi\Test\Api;

use \Evers\SellingPartnerApi\Configuration;
use \Evers\SellingPartnerApi\ApiException;
use \Evers\SellingPartnerApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FeesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Evers\SellingPartnerApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FeesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getMyFeesEstimateForASIN
     *
     * .
     *
     */
    public function testGetMyFeesEstimateForASIN()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMyFeesEstimateForSKU
     *
     * .
     *
     */
    public function testGetMyFeesEstimateForSKU()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
