<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace SellingPartnerApi\Seller\AmazonWarehousingAndDistributionV20240509\Dto;

use SellingPartnerApi\Dto;

final class ProductQuantity extends Dto
{
    protected static array $complexArrayTypes = ['attributes' => ProductAttribute::class];

    /**
     * @param  int  $quantity  Product quantity.
     * @param  string  $sku  The seller or merchant SKU.
     * @param  ProductAttribute[]|null  $attributes  Attributes for this instance of the product. For example, already-prepped, or other attributes that distinguish the product beyond the SKU.
     * @param  ?\DateTimeInterface  $expiration  The expiration date for the SKU. Values are in [ISO 8601](https://developer-docs.amazon.com/sp-api/docs/iso-8601) date-time format.
     * @param  ?PrepDetails  $prepDetails  The preparation details for a product. This contains the prep category, prep owner, and label owner.
     *                                     Prep instructions are generated based on the specified category.
     */
    public function __construct(
        public int $quantity,
        public string $sku,
        public ?array $attributes = null,
        public ?\DateTimeInterface $expiration = null,
        public ?PrepDetails $prepDetails = null,
    ) {}
}
